/** Shown when /api/pricing/public fails or returns empty (e.g. API down, wrong URL). */
export const FALLBACK_PRICING_PLANS = [
  {
    name: 'Starter',
    monthly: 3499,
    quarterly: 2974,
    popular: false,
    features: {
      Posts: 5,
      Reels: 1,
      'Bio Optimization': true,
      'Hashtag Strategy': true,
      'GMB Setup': false,
      'Keyword Integration': false,
      'Social SEO': false,
      'Performance Report': false,
      'Full GMB Management': false,
      'Lead Gen Strategy': false,
      'Priority Support': false,
    },
  },
  {
    name: 'Growth',
    monthly: 4999,
    quarterly: 4249,
    popular: false,
    features: {
      Posts: 8,
      Reels: 2,
      'Bio Optimization': true,
      'Hashtag Strategy': true,
      'GMB Setup': true,
      'Keyword Integration': true,
      'Social SEO': false,
      'Performance Report': false,
      'Full GMB Management': false,
      'Lead Gen Strategy': false,
      'Priority Support': false,
    },
  },
  {
    name: 'Pro',
    monthly: 7999,
    quarterly: 6799,
    popular: true,
    features: {
      Posts: 12,
      Reels: 4,
      'Bio Optimization': true,
      'Hashtag Strategy': true,
      'GMB Setup': true,
      'Keyword Integration': true,
      'Social SEO': true,
      'Performance Report': true,
      'Full GMB Management': false,
      'Lead Gen Strategy': false,
      'Priority Support': false,
    },
  },
  {
    name: 'Elite',
    monthly: 12999,
    quarterly: 11049,
    popular: false,
    features: {
      Posts: 15,
      Reels: 6,
      'Bio Optimization': true,
      'Hashtag Strategy': true,
      'GMB Setup': true,
      'Keyword Integration': true,
      'Social SEO': true,
      'Performance Report': true,
      'Full GMB Management': true,
      'Lead Gen Strategy': true,
      'Priority Support': true,
    },
  },
];
